-- ************************************************************************************
-- This script populates the reviews table with sample data (beer_id must exist)
-- ************************************************************************************
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (1, 1, 'Tasty beer, full of flavors. I enjoyed it!', 5);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (1, 2, 'Totally works for me a lot of Southern Tier Blackwater beers are in my sweet tooth wheelhouse & this is another shining example; great drinkability as well', 4);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (1, 3, 'An incredible beer/stout and a very nice aperitivo. It tastes like superior ingredients put into a Duncan Hines German chocolate cake mix with coconut caramel icing.', 4);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (1, 4, 'Overall I will without a doubt I will be getting more of this, really nice stuff and like always with Southern Tier something you wont forget having. ', 4);

INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (2, 5, 'A sweet milk stout with all the malt characteristics you love but with a bold, unique twist- this beer tastes like a glass full of blueberry pancakes smothered in maple syrup.', 4);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (2, 1, 'Loved this stout. Very dark. Poured from a can. Small head. Smelled like chocolate, blueberry, maple. Just as advertised. The blueberry came through in the taste. Not over powering. Just enough.', 4);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (2, 2, 'These beers can be difficult without a proper alcohol content for warming and backboning. My fault for wanting something more properly stout (and Saugatuck does produce those), but this was more like a sugary soft drink than a beer.', 2);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (2, 3, 'Poured from a can. Pours dark with a very thin tan head. Smell of roasted grain, blueberry and chocolate. Flavor follows the smell. Blueberry flavor is good and feels natural, get some maple flavor in the finish. Interesting.', 3);

INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (3, 4, 'What a great beer. Pours, not too hazy, but just right. Nose is juicy. Head and lacing are beautiful. Ever so slight powdery feeling that I always seems to get with the hazys.', 4);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (3, 5, 'An opaque but glowing light lemon body color, with a supper rich creamy filling bright white head of three fingers. Very fine bubbles in the head, with ring lacing, and a creamy island retention volcano. Settles real slowly looking like a great IPA.', 4);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (3, 1, 'Funny how a nose can misdirect. The nose is a bit acrid and funky but the taste is luscious, fruity and mildly hoppy with plenty of ripe tropical taste in a great package of taste.', 5);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (3, 2, 'Overall: A lovely pale ale when youre in the mood for some FRUIT', 4);

INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (4, 3, ' I do taste watermelon, and a simple, non-descript wheat ale. Its a watermelon wheat, a decent one, best used to rev your engine or quench your thirst.', 3);

INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (5, 4, 'Great new IPA, I enjoyed the taste, body and appearance. Tends to be a little dry, very similar to Fiddlehead. Ive always enjoyed Sierra Nevada Pale Ale, and Hazy Little Thing is a nice complement.', 5);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (5, 5, 'This is just unwavering and completely solid, Im not mind blown but perfectly content with the decision, this is my first beer from SN actually so now im looking more forward to the classic pale ale and the other products.', 4);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (5, 1, 'Hazy golden color with a thin white head that does not linger. Not too hoppy with hints of alkaloids on the nose. It has nice citrus hops with hints of grapefruit. This is a very enjoyable and drinkable IPA.', 3);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (5, 2, 'Not as good as their imperial IPA (Fantastic Haze) - but rather enjoyable and excellent considering the reasonable price point for a case. Great value.', 4);

INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (6, 3, 'Extremely good flavor, smell, and feel. This "palesner" is very good quality for a decent price. A hoppy taste, but not overbearing. A good choice for any occasion. Highly recommended.', 5);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (6, 4, 'Had this in a hotel lobby. Then had several. Best hoppy pils attempt that Ive had. most are decent injections of bitterness during which your left brain thinks youre having a miller lite. This brew has nothin to hide.', 4);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (6, 5, 'Looks super Thin with barely any head and yellow color. Barley and malty scent. Taste out does the look and smell, great barley malt toasted bread taste. Medium light body with medium carbonation. Suprisingly good!', 4);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (6, 1, ' A nice beer. Not quite as hoppy as I expected given the mash-up style but it fits tie pils profile well & is very easy to drink', 3);

INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (7, 2, 'Bottled. Light gold in color. Small head that sticks around. Faint floral smell. Thin on the pallet. Balanced well front to back. More bite on the back end. Nice beer', 4);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (7, 3, 'Good whiff of piney and citrusy hops � in that order. There�s a bit of bready malt aroma way in the background.', 4);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (7, 4, 'Handsome amber brew with plenty of foam in the Dupont chalice. This is not as intensely bitter as typical craft IPAs. But its also quite flavorful without being a fruit bomb. Aroma of lime peel and a Salty dog.', 4);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (7, 5, 'The taste is of citrus (especially grapefruit, some lemon) with piney/floral spicing. Grainy sweet backbone. Bitter, slightly medicinal finish. Alcohol well-integrated (giving just a hint of pepper, but not hot).', 4);

INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (8, 1, 'Stone brewing does a lot of IPAs so it is surprising to find another IPA in their line up. Not really. I find myself gravitating towards the scorpion bowl IPA yet this one is another good IPA from folks who know how to make an IPA.', 4);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (8, 2, 'Non existent head, but nice deep color. Smells hoppy and a little sweet. Name is accurate, it is quite delicious. It�s got a great grain profile and hoppy complexity. Slightly bitter aftertaste but its not bad at all.', 3);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (8, 3, 'I love gritty, dry IPAs with scrubbing carbonation like this. The alcohol again is a bit much.', 3);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (8, 4, ' I really liked this beer a lot; especially nice in a reduced gluten offering. I can drink more before the bloating becomes the obvious.', 4);

INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (10, 1, 'Tasty beer, full of flavors. I enjoyed it!', 5);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (10, 2, 'Totally works for me a lot of Southern Tier Blackwater beers are in my sweet tooth wheelhouse & this is another shining example; great drinkability as well', 4);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (10, 3, 'An incredible beer/stout and a very nice aperitivo. It tastes like superior ingredients put into a Duncan Hines German chocolate cake mix with coconut caramel icing.', 4);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (10, 4, 'Overall I will without a doubt I will be getting more of this, really nice stuff and like always with Southern Tier something you wont forget having. ', 4);

INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (11, 5, 'A sweet milk stout with all the malt characteristics you love but with a bold, unique twist- this beer tastes like a glass full of blueberry pancakes smothered in maple syrup.', 4);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (11, 1, 'Loved this stout. Very dark. Poured from a can. Small head. Smelled like chocolate, blueberry, maple. Just as advertised. The blueberry came through in the taste. Not over powering. Just enough.', 4);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (11, 2, 'These beers can be difficult without a proper alcohol content for warming and backboning. My fault for wanting something more properly stout (and Saugatuck does produce those), but this was more like a sugary soft drink than a beer.', 2);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (11, 3, 'Poured from a can. Pours dark with a very thin tan head. Smell of roasted grain, blueberry and chocolate. Flavor follows the smell. Blueberry flavor is good and feels natural, get some maple flavor in the finish. Interesting.', 3);

INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (12, 4, 'What a great beer. Pours, not too hazy, but just right. Nose is juicy. Head and lacing are beautiful. Ever so slight powdery feeling that I always seems to get with the hazys.', 4);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (12, 5, 'An opaque but glowing light lemon body color, with a supper rich creamy filling bright white head of three fingers. Very fine bubbles in the head, with ring lacing, and a creamy island retention volcano. Settles real slowly looking like a great IPA.', 4);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (12, 1, 'Funny how a nose can misdirect. The nose is a bit acrid and funky but the taste is luscious, fruity and mildly hoppy with plenty of ripe tropical taste in a great package of taste.', 5);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (12, 2, 'Overall: A lovely pale ale when youre in the mood for some FRUIT', 4);

INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (13, 3, ' I do taste watermelon, and a simple, non-descript wheat ale. Its a watermelon wheat, a decent one, best used to rev your engine or quench your thirst.', 3);

INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (14, 4, 'Great new IPA, I enjoyed the taste, body and appearance. Tends to be a little dry, very similar to Fiddlehead. Ive always enjoyed Sierra Nevada Pale Ale, and Hazy Little Thing is a nice complement.', 5);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (14, 5, 'This is just unwavering and completely solid, Im not mind blown but perfectly content with the decision, this is my first beer from SN actually so now im looking more forward to the classic pale ale and the other products.', 4);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (14, 1, 'Hazy golden color with a thin white head that does not linger. Not too hoppy with hints of alkaloids on the nose. It has nice citrus hops with hints of grapefruit. This is a very enjoyable and drinkable IPA.', 3);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (14, 2, 'Not as good as their imperial IPA (Fantastic Haze) - but rather enjoyable and excellent considering the reasonable price point for a case. Great value.', 4);

INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (15, 3, 'Extremely good flavor, smell, and feel. This "palesner" is very good quality for a decent price. A hoppy taste, but not overbearing. A good choice for any occasion. Highly recommended.', 5);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (15, 4, 'Had this in a hotel lobby. Then had several. Best hoppy pils attempt that Ive had. most are decent injections of bitterness during which your left brain thinks youre having a miller lite. This brew has nothin to hide.', 4);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (15, 5, 'Looks super Thin with barely any head and yellow color. Barley and malty scent. Taste out does the look and smell, great barley malt toasted bread taste. Medium light body with medium carbonation. Suprisingly good!', 4);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (15, 1, ' A nice beer. Not quite as hoppy as I expected given the mash-up style but it fits tie pils profile well & is very easy to drink', 3);

INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (16, 2, 'Bottled. Light gold in color. Small head that sticks around. Faint floral smell. Thin on the pallet. Balanced well front to back. More bite on the back end. Nice beer', 4);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (16, 3, 'Good whiff of piney and citrusy hops � in that order. There�s a bit of bready malt aroma way in the background.', 4);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (16, 4, 'Handsome amber brew with plenty of foam in the Dupont chalice. This is not as intensely bitter as typical craft IPAs. But its also quite flavorful without being a fruit bomb. Aroma of lime peel and a Salty dog.', 4);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (16, 5, 'The taste is of citrus (especially grapefruit, some lemon) with piney/floral spicing. Grainy sweet backbone. Bitter, slightly medicinal finish. Alcohol well-integrated (giving just a hint of pepper, but not hot).', 4);

INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (17, 1, 'Stone brewing does a lot of IPAs so it is surprising to find another IPA in their line up. Not really. I find myself gravitating towards the scorpion bowl IPA yet this one is another good IPA from folks who know how to make an IPA.', 4);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (17, 2, 'Non existent head, but nice deep color. Smells hoppy and a little sweet. Name is accurate, it is quite delicious. It�s got a great grain profile and hoppy complexity. Slightly bitter aftertaste but its not bad at all.', 3);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (17, 3, 'I love gritty, dry IPAs with scrubbing carbonation like this. The alcohol again is a bit much.', 3);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (17, 4, ' I really liked this beer a lot; especially nice in a reduced gluten offering. I can drink more before the bloating becomes the obvious.', 4);

INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (19, 1, 'Tasty beer, full of flavors. I enjoyed it!', 5);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (19, 2, 'Totally works for me a lot of Southern Tier Blackwater beers are in my sweet tooth wheelhouse & this is another shining example; great drinkability as well', 4);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (19, 3, 'An incredible beer/stout and a very nice aperitivo. It tastes like superior ingredients put into a Duncan Hines German chocolate cake mix with coconut caramel icing.', 4);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (19, 4, 'Overall I will without a doubt I will be getting more of this, really nice stuff and like always with Southern Tier something you wont forget having. ', 4);

INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (20, 5, 'A sweet milk stout with all the malt characteristics you love but with a bold, unique twist- this beer tastes like a glass full of blueberry pancakes smothered in maple syrup.', 4);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (20, 1, 'Loved this stout. Very dark. Poured from a can. Small head. Smelled like chocolate, blueberry, maple. Just as advertised. The blueberry came through in the taste. Not over powering. Just enough.', 4);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (20, 2, 'These beers can be difficult without a proper alcohol content for warming and backboning. My fault for wanting something more properly stout (and Saugatuck does produce those), but this was more like a sugary soft drink than a beer.', 2);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (20, 3, 'Poured from a can. Pours dark with a very thin tan head. Smell of roasted grain, blueberry and chocolate. Flavor follows the smell. Blueberry flavor is good and feels natural, get some maple flavor in the finish. Interesting.', 3);

INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (21, 4, 'What a great beer. Pours, not too hazy, but just right. Nose is juicy. Head and lacing are beautiful. Ever so slight powdery feeling that I always seems to get with the hazys.', 4);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (21, 5, 'An opaque but glowing light lemon body color, with a supper rich creamy filling bright white head of three fingers. Very fine bubbles in the head, with ring lacing, and a creamy island retention volcano. Settles real slowly looking like a great IPA.', 4);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (21, 1, 'Funny how a nose can misdirect. The nose is a bit acrid and funky but the taste is luscious, fruity and mildly hoppy with plenty of ripe tropical taste in a great package of taste.', 5);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (21, 2, 'Overall: A lovely pale ale when youre in the mood for some FRUIT', 4);

INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (22, 3, ' I do taste watermelon, and a simple, non-descript wheat ale. Its a watermelon wheat, a decent one, best used to rev your engine or quench your thirst.', 3);

INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (23, 4, 'Great new IPA, I enjoyed the taste, body and appearance. Tends to be a little dry, very similar to Fiddlehead. Ive always enjoyed Sierra Nevada Pale Ale, and Hazy Little Thing is a nice complement.', 5);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (23, 5, 'This is just unwavering and completely solid, Im not mind blown but perfectly content with the decision, this is my first beer from SN actually so now im looking more forward to the classic pale ale and the other products.', 4);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (23, 1, 'Hazy golden color with a thin white head that does not linger. Not too hoppy with hints of alkaloids on the nose. It has nice citrus hops with hints of grapefruit. This is a very enjoyable and drinkable IPA.', 3);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (23, 2, 'Not as good as their imperial IPA (Fantastic Haze) - but rather enjoyable and excellent considering the reasonable price point for a case. Great value.', 4);

INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (24, 3, 'Extremely good flavor, smell, and feel. This "palesner" is very good quality for a decent price. A hoppy taste, but not overbearing. A good choice for any occasion. Highly recommended.', 5);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (24, 4, 'Had this in a hotel lobby. Then had several. Best hoppy pils attempt that Ive had. most are decent injections of bitterness during which your left brain thinks youre having a miller lite. This brew has nothin to hide.', 4);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (24, 5, 'Looks super Thin with barely any head and yellow color. Barley and malty scent. Taste out does the look and smell, great barley malt toasted bread taste. Medium light body with medium carbonation. Suprisingly good!', 4);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (24, 1, ' A nice beer. Not quite as hoppy as I expected given the mash-up style but it fits tie pils profile well & is very easy to drink', 3);

INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (25, 2, 'Bottled. Light gold in color. Small head that sticks around. Faint floral smell. Thin on the pallet. Balanced well front to back. More bite on the back end. Nice beer', 4);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (25, 3, 'Good whiff of piney and citrusy hops � in that order. There�s a bit of bready malt aroma way in the background.', 4);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (25, 4, 'Handsome amber brew with plenty of foam in the Dupont chalice. This is not as intensely bitter as typical craft IPAs. But its also quite flavorful without being a fruit bomb. Aroma of lime peel and a Salty dog.', 4);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (25, 5, 'The taste is of citrus (especially grapefruit, some lemon) with piney/floral spicing. Grainy sweet backbone. Bitter, slightly medicinal finish. Alcohol well-integrated (giving just a hint of pepper, but not hot).', 4);

INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (26, 1, 'Stone brewing does a lot of IPAs so it is surprising to find another IPA in their line up. Not really. I find myself gravitating towards the scorpion bowl IPA yet this one is another good IPA from folks who know how to make an IPA.', 4);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (26, 2, 'Non existent head, but nice deep color. Smells hoppy and a little sweet. Name is accurate, it is quite delicious. It�s got a great grain profile and hoppy complexity. Slightly bitter aftertaste but its not bad at all.', 3);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (26, 3, 'I love gritty, dry IPAs with scrubbing carbonation like this. The alcohol again is a bit much.', 3);
INSERT INTO reviews (beer_id, reviewer_id, review_text, star_rating) values (26, 4, ' I really liked this beer a lot; especially nice in a reduced gluten offering. I can drink more before the bloating becomes the obvious.', 4);
